name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12' # Use Node.js version >=12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build front-end assets
      - name: Build assets
        run: npm run build

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 6: Deploy to S3
      - name: Sync files to S3
        run: |
          aws s3 sync ./static s3://${{ secrets.S3_BUCKET_NAME }} --delete
